[package]
name = "io_parser"
version = "0.1.5"
edition = "2021"
license = "MIT"
description = "Crate that parses IO-reads"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
